# Generated by Django 5.0.3 on 2024-06-23 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_app', '0002_alter_favourite_recipe_favourite_recipe_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
    ]
